name: 'Test Execution Validation'

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - '**'

jobs:
  build-push-deploy:
    name: 'Execute Test Cases'
    runs-on: ubuntu-latest
    if: ${{ (github.event.action != 'closed' == true) }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # gCloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.DEV_SA_KEY }}
        project_id: skyviewer
        export_default_credentials: true
    
    # Get secrets
    - name: Get env
      run: gcloud secrets versions access latest --secret=craft-dam-plugin-env > ./tests/.env

    # Composer install
    - name: Install Composer dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.4"
        php_extensions: zip
        command: install

    - name: Connect to SQL proxy
      uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: ${{ secrets.DEV_SA_KEY }}
        instance: skyviewer:us-central1:main-rubin-site-db-replica

    # Execute those tests
    - name: Execute tests
      run: php vendor/bin/codecept run unit
      # uses: joelwmale/codeception-action@master
      # env:
      #   ENV_FILE: ./tests/.env
